
## APM-server.yml
apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true

output.elasticsearch:
  hosts: ["http://localhost:9200"] # change with your actual ip of ES
  username: "elastic"   # change with your elastic search username & pass
  password: "DIgea+J4ogc1ycA*Whtu"

setup.kibana:
  host: "http://localhost:5601"
  username: "elastic"
  password: "DIgea+J4ogc1ycA*Whtu"
